name: mldevops-p4-deploy
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip=20.3.3
  - pip:
    - numpy==1.21.6
    - pandas==1.1.5
    - scikit-learn==0.24.1
    - pytest==6.2.2
    - requests==2.31.0
    - fastapi==0.63.0
    - uvicorn==0.25.0
    - gunicorn=21.2.0
    - flake8==7.0.0
